const ASSETS={hero:'UI素材/hero.png',states:'UI素材/states.png',frames:'UI素材/frames.png'};
const fallback={items:[{id:'demo-1',name:'桌面收纳架',gift_type:'实用型',category:'办公用品',price:[59,129],objects:['熟人朋友','青年'],scenes:['生日','感谢/探望'],interests:['居家','生活方式'],styles:['实用','简洁'],age:['青年','中年'],taboos:['已有同类'],reason:'适合在生日等场景表达心意，兼顾日常使用与空间秩序。',focus:'关注尺寸、材质、使用门槛和售后信息。',send:'用轻便包装，见面时自然递出并附一张短卡。'},{id:'demo-2',name:'手写信件套装',gift_type:'情绪纪念型',category:'情绪礼物',price:[29,79],objects:['亲密关系','长辈/家人'],scenes:['生日','纪念日'],interests:['兴趣探索','生活方式'],styles:['有仪式感','简洁'],age:['青年','中年','老年'],taboos:['已有同类'],reason:'把重要时刻写下来，适合需要表达与纪念的关系。',focus:'关注纸张、书写体验和收纳方式。',send:'选择安静时机，把信件放在礼盒最上层。'},{id:'demo-3',name:'香薰蜡烛',gift_type:'氛围审美型',category:'氛围礼物',price:[69,199],objects:['熟人朋友','亲密关系'],scenes:['生日','纪念日'],interests:['居家','生活方式'],styles:['有仪式感','简洁'],age:['青年','中年'],taboos:['不符合对方兴趣'],reason:'为日常空间增加温柔氛围，适合重视生活感受的人。',focus:'关注香型、燃烧时长和使用安全。',send:'搭配一张小卡片，提醒首次点燃前阅读安全说明。'}]};
let data=fallback, state={screen:'home',step:1,answers:{object:'',scene:'',budget:'',budgetMode:'single',interest:[],age:'',style:[],taboo:[]},results:[],near:[],tab:'high',detail:null,send:null,feedback:'',share:{summary:true,high:true,near:false,reason:true,send:true},loading:false};
const objects=['亲密关系','熟人朋友','普通社交','长辈/家人'], scenes=['生日','节日/节气','纪念日','感谢/探望'], interests=['居家','生活方式','运动','美食','手作','数码','阅读','旅行'], ages=['青年','中年','老年'], styles=['实用','简洁','有仪式感','安心'], taboos=['已有同类','不符合对方兴趣','食物过敏','饮食禁忌'];
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function priceRange(){const n=Number(state.answers.budget);if(!n||n<1)return null;const d=n<100?Math.max(n*.3,20):50;return [Math.max(0,n-d),n+d]}
function overlap(a,b){const l=Math.max(a[0],b[0]),r=Math.min(a[1],b[1]);return Math.max(0,r-l)/Math.max(1,a[1]-a[0])}
function score(item,relax=''){const a=state.answers, fields=[['object',25,item.objects],['scene',20,item.scenes],['interest',20,item.interests],['age',20,item.age],['style',10,item.styles]];let total=0,max=0;for(const [key,w,vals] of fields){if(!a[key]||(Array.isArray(a[key])&&!a[key].length)||key===relax)continue;max+=w;const v=Array.isArray(a[key])?a[key]:[a[key]];if(v.some(x=>vals?.includes(x)))total+=w}const p=priceRange();const po=p?overlap(p,item.price):0;max+=15;total+=15*po;return {score:Math.round(max?total/max*100:0),po,relaxed:relax}}
function compute(){const a=state.answers;const base=data.items.filter(x=>!(x.taboos||[]).some(t=>(a.taboo||[]).includes(t)));const scored=base.map(x=>({...x,...score(x)})).sort((x,y)=>y.score-x.score);state.results=scored.filter(x=>x.score>=80&&x.po>0).slice(0,5);if(!state.results.length)state.results=scored.filter(x=>x.po>0).slice(0,3);const relaxes=['scene','age','interest'];state.near=[];const used=new Set(state.results.map(x=>x.id));for(const r of relaxes){const s=base.map(x=>({...x,...score(x,r),relaxed:r})).filter(x=>x.po>0&&!used.has(x.id)).sort((x,y)=>y.score-x.score);for(const item of s.slice(0,2)){if(used.has(item.id))continue;used.add(item.id);state.near.push(item);if(state.near.length>=5)break}if(state.near.length>=5)break}}
function tagList(arr){return (arr||[]).slice(0,3).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}
function render(){const app=$('#app');if(state.screen==='home')return app.innerHTML=home();if(state.screen==='wizard')return app.innerHTML=wizard();if(state.screen==='results')return app.innerHTML=results();if(state.screen==='share')return app.innerHTML=share();}
function home(){return `<section class="shell hero"><div class="hero-copy"><div class="eyebrow">A small ritual for a thoughtful gift</div><h1>送礼<br><em>大王</em></h1><p class="hero-lede">用更少的时间，选一份更有心意的礼物。</p><p class="story">我曾为很多朋友准备过礼物，后来把那些“刚刚好”的经验整理成一套可以解释、可以分享的小工具。</p><button class="primary" data-action="start">开始选礼物 <span aria-hidden="true">→</span></button><p class="step-label" style="margin-top:15px">无需登录，选择 3 项即可获得推荐</p></div><div class="hero-art"><img src="${ASSETS.hero}" alt="手绘的礼盒、花束与贺卡"><div class="hero-caption">先想起对方，再想起礼物。<br><span style="color:var(--coral)">From experience, with care.</span></div></div></section>`}
function wizard(){const s=state.step;let title='',body='';if(s===1){title='送给谁？';body=choiceGrid(objects,'object')}if(s===2){title='为了什么时刻？';body=choiceGrid(scenes,'scene')}if(s===3){title='预算大约是多少？';body=`<div class="field-row"><div class="field"><label for="budget">单一金额（元）</label><input id="budget" type="number" min="1" step="1" value="${esc(state.answers.budget)}" placeholder="例如 200" aria-describedby="budget-error"><div id="budget-error" class="error"></div></div><div class="field"><label>常用档位</label><div class="summary">${[80,150,300,500].map(n=>`<button class="tag ${Number(state.answers.budget)===n?'accent':''}" data-budget="${n}">¥${n}</button>`).join('')}</div></div></div><div class="hint">单一金额按 ±50 元匹配；低于 100 元时按 ±30%，最低浮动 20 元。</div>`}if(s===4){title='补充一点兴趣（可跳过）';body=multiGrid(interests,'interest')}if(s===5){title='大概年龄（可跳过）';body=choiceGrid(ages,'age',true)}if(s===6){title='偏爱的风格（可跳过）';body=multiGrid(styles,'style')}if(s===7){title='明确禁忌（可跳过）';body=multiGrid(taboos,'taboo')}const total=s<=3?3:4;const idx=s<=3?s:s-3;return `<section class="flow-shell"><div class="section-head"><div><div class="kicker">${s<=3?'必填 3 步':'精调 · 可跳过'}</div><h2>${title}</h2></div><div><div class="step-label">${s<=3?`第 ${s} / 3 步`:`精调第 ${idx} / 4 项`}</div><div class="progress">${Array.from({length:total},(_,i)=>`<i class="${i<idx?'active':''}"></i>`).join('')}</div></div></div>${body}<div class="form-actions"><button class="secondary" data-action="back">← 返回</button><button class="primary" data-action="next">${s===3?'查看第一版推荐':s===7?'查看推荐':'继续'} →</button></div></section>`}
function choiceGrid(items,key,optional=false){return `<div class="option-grid">${items.map(x=>`<button class="option ${state.answers[key]===x?'selected':''}" data-choice="${key}" data-value="${esc(x)}"><span>${esc(x)}${optional?'<small>可跳过</small>':''}</span><span class="check">${state.answers[key]===x?'✓':''}</span></button>`).join('')}</div>`}
function multiGrid(items,key){const arr=state.answers[key]||[];return `<p class="step-label">可以选择一个或多个</p><div class="option-grid">${items.map(x=>`<button class="option ${arr.includes(x)?'selected':''}" data-multi="${key}" data-value="${esc(x)}"><span>${esc(x)}</span><span class="check">${arr.includes(x)?'✓':''}</span></button>`).join('')}</div>`}
function tabooGrid(){const arr=state.answers.taboo||[];const none=arr.includes('无特别需要避开的');const options=['不想送重复的东西','ta对这类礼物没兴趣','有食物过敏','有饮食限制'];return `<p class="step-label">选中后，我们会自动避开相关礼物</p><div class="option-grid"><button class="option ${none?'selected':''}" data-taboo-clear="true"><span>没有特别需要避开的</span><span class="check">${none?'✓':''}</span></button>${options.map((label,i)=>{const raw=taboos[i];return `<button class="option ${arr.includes(raw)?'selected':''}" data-multi="taboo" data-value="${esc(raw)}"><span>${label}</span><span class="check">${arr.includes(raw)?'✓':''}</span></button>`}).join('')}</div>`}
function giftCard(x,near=false){return `<article class="gift-card"><div class="score">${near?'相近推荐 · 放宽'+({scene:'场景',age:'年龄',interest:'兴趣'}[x.relaxed]||'条件'):`高度匹配 · ${x.score} 分`}</div><h3>${esc(x.name)}</h3><div class="gift-meta">${esc(x.gift_type)} · ${esc(x.category)}<br>¥${x.price[0]}–¥${x.price[1]}</div><div class="summary" style="margin-top:13px">${tagList(x.objects)}${tagList(x.scenes)}</div><p class="reason">${esc(x.reason)}</p><div class="gift-foot"><button class="mini-btn" data-detail="${esc(x.id)}">查看详情</button><button class="mini-btn" data-send="${esc(x.id)}">怎么送</button></div></article>`}
function results(){const list=state.tab==='high'?state.results:state.near;return `<section class="result-shell"><div class="result-head"><div><div class="kicker">你的送礼地图</div><h2>先看一眼，<br>再决定心意。</h2><div class="summary">${tagList([state.answers.object,state.answers.scene,state.answers.budget?`预算 ¥${state.answers.budget}`:''])}</div></div><div class="result-actions"><button class="secondary" data-action="edit">修改条件</button><button class="secondary" data-action="shuffle">换一组</button></div></div><div class="tabs"><button class="tab ${state.tab==='high'?'active':''}" data-tab="high">高度匹配（${state.results.length}）</button><button class="tab ${state.tab==='near'?'active':''}" data-tab="near">相近推荐（${state.near.length}）</button></div>${state.tab==='near'&&state.near.length?'<div class="hint">这些选择放宽了一个条件，仍保留预算和禁忌过滤。</div>':''}<div class="gift-list">${list.length?list.map(x=>giftCard(x,state.tab==='near')).join(''):'<div class="empty">暂时没有完全符合的推荐。可以返回修改预算或条件，再试一次。</div>'}</div><div class="send-panel"><div class="send-copy"><div class="kicker">A little extra</div><h3>把礼物送得更像你</h3><p>从一份推荐开始，再加上一个合适的时机、一句自己的话。</p><button class="primary" data-action="share">编辑分享内容 →</button></div><div class="send-box">${state.send?`<strong>${esc(state.send.name)}</strong><p>${esc(state.send.text)}</p>`:'点击任意礼物的“怎么送”，查看包装、时机和贺卡文案。'}</div></div><div class="feedback"><strong>这组推荐对你有帮助吗？</strong><div class="feedback-buttons"><button class="secondary" data-feedback="yes">有帮助</button><button class="secondary" data-feedback="no">没帮助</button></div>${state.feedback?`<span class="tag accent">已记录：${state.feedback==='yes'?'谢谢你的肯定':'收到，我们会继续调整'}</span>`:''}</div></section>`}
function share(){const active=state.results[0]||state.near[0];const summary=`送给 ${state.answers.object||'对方'} · ${state.answers.scene||'某个特别时刻'}`;return `<section class="result-shell"><div class="section-head"><div><div class="kicker">Share a little care</div><h2>做一张<br>可以转发的心意卡。</h2></div><button class="secondary" data-action="results">← 返回推荐</button></div><div class="share-controls"><div><p class="step-label">选择要放进图片的内容</p><div class="check-list">${[['summary','条件摘要'],['high','高度匹配'],['near','相近推荐'],['reason','推荐理由'],['send','怎么送']].map(([k,l])=>`<label class="check-item"><input type="checkbox" data-share="${k}" ${state.share[k]?'checked':''}>${l}</label>`).join('')}</div><div class="share-actions"><button class="primary" data-action="generate">生成分享图</button><button class="secondary" data-action="copy">复制纯文本</button></div></div><div><p class="step-label">实时预览 · 1080 × 1920</p><div class="preview"><h3>送礼大王</h3>${state.share.summary?`<p>${esc(summary)}</p>`:''}${state.share.high&&state.results.length?`<p><b>高度匹配</b><br>${state.results.slice(0,3).map(x=>esc(x.name)).join(' · ')}</p>`:''}${state.share.near&&state.near.length?`<p><b>相近推荐</b><br>${state.near.slice(0,2).map(x=>esc(x.name)).join(' · ')}</p>`:''}${state.share.reason&&active?`<p><b>为什么</b><br>${esc(active.reason)}</p>`:''}${state.share.send&&active?`<p><b>怎么送</b><br>${esc(active.send)}</p>`:''}</div></div></div></section>`}
async function loadData(){try{const r=await fetch('送礼大王_礼物数据集_MVP_v1.8.json');if(!r.ok)throw Error();const j=await r.json();if(j.items?.length)data=j}catch(e){toast('直接打开时浏览器限制读取 JSON，当前使用演示数据；用本地静态服务器可加载完整礼物库。')}}
function openDetail(id){const x=data.items.find(i=>i.id===id)||state.results.find(i=>i.id===id)||state.near.find(i=>i.id===id);if(!x)return;state.detail=x;$('#dialog-root').innerHTML=`<div class="drawer-backdrop" data-action="close-detail"></div><aside class="drawer" role="dialog" aria-modal="true" aria-labelledby="detail-title"><button class="drawer-close" data-action="close-detail" aria-label="关闭详情">×</button><div class="kicker">${esc(x.gift_type)}</div><h2 id="detail-title">${esc(x.name)}</h2><p class="gift-meta">${esc(x.category)} · ¥${x.price[0]}–${x.price[1]}</p><div class="detail-block"><h4>适合谁 / 什么时刻</h4><p>${tagList(x.objects)} ${tagList(x.scenes)}</p></div><div class="detail-block"><h4>匹配分解</h4><p>对象、场景、预算与已填写偏好共同参与评分；当前匹配约 <strong>${x.score||'—'} 分</strong>。</p></div><div class="detail-block"><h4>推荐理由</h4><p>${esc(x.reason)}</p></div><div class="detail-block"><h4>购买时关注什么</h4><p>${esc(x.focus)}</p></div><div class="detail-block"><h4>常见踩坑</h4><p>先确认是否已有同类，留意尺寸、材质、使用门槛与安全说明，不用夸张功效替代真实需求。</p></div><button class="primary" data-send="${esc(x.id)}">查看怎么送 →</button></aside>`;$('.drawer-close')?.focus()}
function bind(){document.addEventListener('click',e=>{const t=e.target.closest('[data-action],[data-choice],[data-multi],[data-budget],[data-tab],[data-detail],[data-send],[data-feedback]');if(!t)return;if(t.dataset.action==='start'){state.screen='wizard';state.step=1;render();return}if(t.dataset.action==='home'){state.screen='home';render();return}if(t.dataset.action==='reset'){state={...state,screen:'home',step:1,answers:{object:'',scene:'',budget:'',budgetMode:'single',interest:[],age:'',style:[],taboo:[]},results:[],near:[]};render();return}if(t.dataset.choice){state.answers[t.dataset.choice]=t.dataset.value;render();return}if(t.dataset.multi){const a=state.answers[t.dataset.multi]||[];state.answers[t.dataset.multi]=a.includes(t.dataset.value)?a.filter(x=>x!==t.dataset.value):[...a,t.dataset.value];render();return}if(t.dataset.budget){state.answers.budget=t.dataset.budget;render();return}if(t.dataset.action==='back'){if(state.step>1){state.step--;render()}else{state.screen='home';render()}return}if(t.dataset.action==='next'){if(state.step===3){const n=Number(state.answers.budget);if(!n||n<=0){$('#budget-error').textContent='请输入大于 0 的有效金额，或选择常用档位';return}compute();state.screen='results';state.tab='high';render();return}if(state.step===7){compute();state.screen='results';render();return}state.step++;render();return}if(t.dataset.action==='edit'){state.screen='wizard';state.step=1;render();return}if(t.dataset.action==='results'){state.screen='results';render();return}if(t.dataset.action==='shuffle'){const arr=state.tab==='high'?state.results:state.near;arr.push(...arr.splice(0,1));render();return}if(t.dataset.tab){state.tab=t.dataset.tab;render();return}if(t.dataset.detail){openDetail(t.dataset.detail);return}if(t.dataset.send){const x=data.items.find(i=>i.id===t.dataset.send)||state.results.find(i=>i.id===t.dataset.send)||state.near.find(i=>i.id===t.dataset.send);if(x){state.send={name:x.name,text:`包装建议：${x.send}\n\n送礼时机：选择对方不匆忙的时刻，留一点打开和回应的空间。\n\n贺卡文案：愿这份小礼物，替你把在意说得更具体。`};$('#dialog-root').innerHTML='';render();toast('已打开“怎么送”建议');}return}if(t.dataset.action==='close-detail'){ $('#dialog-root').innerHTML='';return}if(t.dataset.feedback){state.feedback=t.dataset.feedback;render();toast('反馈已记录，仅保存在本地演示中');return}if(t.dataset.action==='share'){state.screen='share';render();return}if(t.dataset.action==='copy'){const txt=$('.preview')?.innerText||'';navigator.clipboard?.writeText(txt).then(()=>toast('已复制纯文本')).catch(()=>toast('复制失败，请手动选择预览文字'));return}if(t.dataset.action==='generate'){toast('正在生成 1080 × 1920 分享图…');setTimeout(()=>toast('分享图生成演示完成，可复制预览内容'),900);return}});document.addEventListener('change',e=>{if(e.target.dataset.share){state.share[e.target.dataset.share]=e.target.checked;render()}})}
function openDetail(id){const x=state.results.find(i=>i.id===id)||state.near.find(i=>i.id===id)||data.items.find(i=>i.id===id);if(!x)return;state.detail=x;$('#dialog-root').innerHTML=`<div class="drawer-backdrop" data-action="close-detail"></div><aside class="drawer" role="dialog" aria-modal="true" aria-labelledby="detail-title"><button class="drawer-close" data-action="close-detail" aria-label="关闭详情">×</button><div class="kicker">${esc(x.gift_type)}</div><h2 id="detail-title">${esc(x.name)}</h2><p class="gift-meta">${esc(x.category)} · ¥${x.price[0]}–${x.price[1]}</p><div class="detail-block"><h4>适合谁 / 什么时刻</h4><p>${tagList(x.objects)} ${tagList(x.scenes)}</p></div><div class="detail-block"><h4>匹配分解</h4><p>对象、场景、预算与已填写偏好共同参与评分；当前匹配约 <strong>${x.score||'—'} 分</strong>。</p></div><div class="detail-block"><h4>推荐理由</h4><p>${esc(x.reason)}</p></div><div class="detail-block"><h4>购买时关注什么</h4><p>${esc(x.focus)}</p></div><div class="detail-block"><h4>常见踩坑</h4><p>先确认是否已有同类，留意尺寸、材质、使用门槛与安全说明，不用夸张功效替代真实需求。</p></div><button class="primary" data-send="${esc(x.id)}">查看怎么送 →</button></aside>`;$('.drawer-close')?.focus()}
const homeOriginal=home;home=()=>homeOriginal().replace('送礼指南工具 · MVP','把心意说清楚').replace('无需登录，选择 3 项即可获得推荐','不需要登录，几秒钟就能开始').replace(`<img src="${ASSETS.hero}" alt="手绘的礼盒、花束与贺卡">`,`<div class="asset-crop asset-hero" role="img" aria-label="手绘的礼盒、花束与贺卡"></div>`);
const wizardOriginal=wizard;wizard=()=>wizardOriginal().replace('必填 3 步','先从核心信息开始').replace('精调 · 可跳过','再补充一点偏好').replace('补充一点兴趣（可跳过）','ta的兴趣是什么').replace('明确禁忌（可跳过）','有哪些情况需要避开？').replace("body=multiGrid(taboos,'taboo')","body=tabooGrid()").replace(/第 \d+ \/ 3 步/g,'正在填写').replace(/精调第 \d+ \/ 4 项/g,'');
const resultsOriginal=results;results=()=>resultsOriginal().replace('查看第一版推荐','查看初步推荐').replace('<button class="secondary" data-action="edit">修改条件</button>','<button class="secondary" data-action="edit">修改条件</button><button class="secondary" data-action="refine">补充喜好</button>');
const shareOriginal=share;share=()=>shareOriginal().replace('查看第一版推荐','查看初步推荐');
function giftCard(x,near=false){const reasonOpen=state.expandedReason===x.id;const sendOpen=state.expandedSend===x.id;return `<article class="gift-card compact-gift"><div class="score">${near?'相近推荐 · 放宽'+({scene:'场景',age:'年龄',interest:'兴趣'}[x.relaxed]||'条件'):`高度匹配 · ${x.score} 分`}</div><h3>${esc(x.name)}</h3><div class="gift-meta">${esc(x.gift_type)} · ${esc(x.category)}<br>¥${x.price[0]}–¥${x.price[1]}</div><div class="summary" style="margin-top:10px">${tagList(x.objects)}${tagList(x.scenes)}</div>${reasonOpen?`<div class="inline-detail"><b>为什么推荐</b><p>${esc(x.reason)}</p></div>`:''}${sendOpen?`<div class="inline-detail send-expand"><p><b>包装建议</b>${esc(x.send||'选择轻便包装，留一点打开和回应的空间。')}</p><p><b>赠送时机</b>选择对方不匆忙的时刻，留一点打开和回应的空间。</p><p><b>惊喜设计</b>把礼物放在对方会经过的位置，或搭配一张手写小卡。</p><p><b>贺卡文案</b>愿这份小礼物，替你把在意说得更具体。</p></div>`:''}<div class="gift-foot"><button class="mini-btn" data-action="toggle-reason" data-reason-id="${esc(x.id)}">${reasonOpen?'收起理由':'为什么推荐'}</button><button class="mini-btn" data-action="expand-send" data-send-id="${esc(x.id)}">${sendOpen?'收起怎么送':'怎么送'}</button><button class="mini-btn" data-detail="${esc(x.id)}">完整详情</button></div></article>`}
function giftCard(x,near=false){const expanded=state.expandedSend===x.id;const short=(x.send||'').split('；')[0]||'见面时自然递出，留一点打开和回应的空间。';return `<article class="gift-card compact-gift"><div class="score">${near?'相近推荐 · 放宽'+({scene:'场景',age:'年龄',interest:'兴趣'}[x.relaxed]||'条件'):`高度匹配 · ${x.score} 分`}</div><h3>${esc(x.name)}</h3><div class="gift-meta">${esc(x.gift_type)} · ${esc(x.category)}<br>¥${x.price[0]}–¥${x.price[1]}</div><div class="summary" style="margin-top:10px">${tagList(x.objects)}${tagList(x.scenes)}</div><p class="reason">${esc(x.reason)}</p><div class="send-glimpse"><div><b>适合时机</b><span>见面或饭后，自然递出</span></div><div><b>一句话</b><span>“看到它的时候，想到了你。”</span></div></div>${expanded?`<div class="send-expand"><p><b>包装建议</b>${esc(x.send||'选择轻便包装，留一点打开和回应的空间。')}</p><p><b>赠送时机</b>选择对方不匆忙的时刻，留一点打开和回应的空间。</p><p><b>惊喜设计</b>把礼物放在对方会经过的位置，或搭配一张手写小卡。</p><p><b>贺卡文案</b>愿这份小礼物，替你把在意说得更具体。</p></div>`:''}<div class="gift-foot"><button class="mini-btn" data-detail="${esc(x.id)}">查看详情</button><button class="mini-btn" data-action="expand-send" data-send-id="${esc(x.id)}">${expanded?'收起怎么送':'展开怎么送'}</button></div></article>`}
const resultsCompactOriginal=results;results=()=>resultsCompactOriginal().replace('<button class="secondary" data-action="edit">修改条件</button><button class="secondary" data-action="refine">补充喜好</button>','<button class="secondary" data-action="edit">修改条件</button><button class="secondary" data-action="refine">补充喜好</button><button class="secondary" data-action="share">分享</button>');
const resultsNoRelaxHint=results;results=()=>resultsNoRelaxHint().replace('<div class="hint">这些选择放宽了一个条件，仍保留预算和禁忌过滤。</div>','');
const homeCopyOriginal=home;home=()=>homeCopyOriginal().replace('我曾为很多朋友准备过礼物，后来把那些“刚刚好”的经验整理成一套可以解释、可以分享的小工具。','准备礼物的人比收到礼物的人更早感到幸福').replace('A small ritual for a thoughtful gift','A small ritual for a thoughtful gift');
const wizardHintOriginal=wizard;wizard=()=>wizardHintOriginal().replace('单一金额按 ±50 元匹配；低于 100 元时按 ±30%，最低浮动 20 元。','填写你愿意为这次礼物准备的金额，我们会按合理浮动范围帮你匹配合适的礼物。').replace('查看第一版推荐','查看初步推荐');
function giftCard(x,near=false){const reasonOpen=state.expandedReason===x.id;const sendOpen=state.expandedSend===x.id;return `<article class="gift-card compact-gift"><div class="score">${near?'相近推荐 · 放宽'+({scene:'场景',age:'年龄',interest:'兴趣'}[x.relaxed]||'条件'):`高度匹配 · ${x.score} 分`}</div><h3>${esc(x.name)}</h3><div class="gift-meta">${esc(x.gift_type)} · ${esc(x.category)}<br>¥${x.price[0]}–¥${x.price[1]}</div><div class="summary" style="margin-top:10px">${tagList(x.objects)}${tagList(x.scenes)}</div>${reasonOpen?`<div class="inline-detail"><b>为什么推荐</b><p>${esc(x.reason)}</p></div>`:''}${sendOpen?`<div class="inline-detail send-expand"><p><b>包装建议</b>${esc(x.send||'选择轻便包装，留一点打开和回应的空间。')}</p><p><b>赠送时机</b>选择对方不匆忙的时刻，留一点打开和回应的空间。</p><p><b>惊喜设计</b>把礼物放在对方会经过的位置，或搭配一张手写小卡。</p><p><b>贺卡文案</b>愿这份小礼物，替你把在意说得更具体。</p></div>`:''}<div class="gift-foot"><button class="mini-btn" data-action="toggle-reason" data-reason-id="${esc(x.id)}">${reasonOpen?'收起理由':'为什么推荐'}</button><button class="mini-btn" data-action="expand-send" data-send-id="${esc(x.id)}">${sendOpen?'收起怎么送':'怎么送'}</button><button class="mini-btn" data-detail="${esc(x.id)}">完整详情</button></div></article>`}
const renderOriginal=render;render=function(){renderOriginal();if(state.screen==='share'&&!document.querySelector('[data-action="save-image"]')){$('.share-actions')?.insertAdjacentHTML('beforeend','<button class="secondary" data-action="save-image">保存图片</button>');$('.preview')?.insertAdjacentHTML('afterbegin','<div class="asset-share-corner" aria-hidden="true"></div>')}};
function drawShare(){const c=document.createElement('canvas');c.width=1080;c.height=1920;const x=c.getContext('2d');x.fillStyle='#fbf8f1';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#ef6b55';x.lineWidth=4;x.strokeRect(40,40,1000,1840);x.fillStyle='#142d2b';x.font='700 64px Georgia';x.fillText('送礼大王',90,150);x.font='32px Georgia';let y=240;const lines=($('.preview')?.innerText||'').split('\n');for(const line of lines){const words=line.match(/.{1,18}/g)||[''];for(const part of words){x.fillText(part,90,y);y+=48;if(y>1790){x.fillStyle='#ef6b55';x.fillText('下一页请继续查看',90,1815);break}}}return c.toDataURL('image/png')}
document.addEventListener('input',e=>{if(e.target.id==='budget')state.answers.budget=e.target.value});document.addEventListener('click',e=>{const clear=e.target.closest('[data-taboo-clear]');if(clear){state.answers.taboo=[];render();return}const expand=e.target.closest('[data-action="expand-send"]');if(expand){state.expandedSend=state.expandedSend===expand.dataset.sendId?'':expand.dataset.sendId;render();return}const reason=e.target.closest('[data-action="toggle-reason"]');if(reason){state.expandedReason=state.expandedReason===reason.dataset.reasonId?'':reason.dataset.reasonId;render();return}const specific=e.target.closest('[data-multi="taboo"]');if(specific){state.answers.taboo=(state.answers.taboo||[]).filter(x=>x!=='无特别需要避开的');}if(e.target.closest('[data-action="refine"]')){state.screen='wizard';state.step=4;render();return}if(e.target.closest('[data-action="save-image"]')){const a=document.createElement('a');a.download='送礼大王-分享图.png';a.href=drawShare();a.click();toast('分享图已保存');}});

function giftCard(x,near=false){const match=near?'相近推荐':`高度匹配 · ${x.score} 分`;return `<button type="button" class="gift-choice" data-detail="${esc(x.id)}" aria-label="查看${esc(x.name)}的完整建议"><span class="gift-choice-match">${match}</span><span class="gift-choice-name">${esc(x.name)}</span><span class="gift-choice-price">¥${x.price[0]}–¥${x.price[1]}</span><span class="gift-choice-arrow" aria-hidden="true">&rsaquo;</span></button>`}

function sendAdvice(x){const wrapping={实用型:'使用素色纸盒或布袋，保留礼物本身的利落感；可附一张简短的使用提示。',情绪纪念型:'用有触感的包装纸或信封包好，把贺卡放在最上层，让文字先于礼物被看见。',兴趣爱好型:'包装保持简洁，在系带或小卡上加入与兴趣相关的颜色或细节，不必堆叠装饰。',体验互动型:'用邀请函或折页卡代替传统礼盒，清楚写出体验内容，并为时间选择留出余地。',氛围审美型:'使用素色薄纸与细绳，避免压住或遮挡礼物的造型和质感。',消耗享用型:'用便于携带的礼袋或纸盒包装，并附上保存方式、食用顺序等必要说明。',安心照料型:'选择干净、容易拆开的包装，随礼物附上简单明确的使用和清洁提示。'}[x.gift_type]||'选择简洁、容易打开的包装，避免过度装饰抢走礼物本身的注意力。';const surprise={实用型:'把礼物放在它最可能被使用的位置，让对方在真实场景里自然发现。',情绪纪念型:'先用一张照片、一句话或一个共同记忆作为线索，再揭晓礼物。',兴趣爱好型:'从对方最近提到的一次兴趣话题切入，让礼物成为那段聊天的回应。',体验互动型:'先给出两个可选时间或玩法，让对方参与决定，惊喜之外也保留舒适感。',氛围审美型:'提前布置在书桌、餐桌或床头等自然场景里，让礼物融入当下的氛围。',消耗享用型:'安排一次可以共同品尝或使用的短暂时刻，让礼物和具体记忆连接起来。',安心照料型:'在对方真正需要它的日常时刻送出，比隆重揭晓更能体现体贴。'}[x.gift_type]||'搭配一张手写小卡，在对方不匆忙时自然递出。';const timing=state.answers.scene==='生日'?'聚会进入放松阶段、切蛋糕之后或分别之前送出，避免刚见面时让对方忙着照顾礼物。':state.answers.scene==='纪念日'?'选择可以单独相处、不被打断的时刻，让打开礼物成为当天的一段完整记忆。':state.answers.scene==='感谢/探望'?'坐下聊过一会儿、准备离开前送出，表达心意但不给对方造成招待压力。':state.answers.scene==='节日/节气'?'见面后的自然空档送出，或提前一天送到，让礼物有时间进入节日氛围。':'选择对方不赶时间、能够从容打开和回应的时刻。';const card=state.answers.object==='亲密关系'?'看到它时想到了你。希望这份小心意，能陪你把普通日子也过得更舒服一点。':state.answers.object==='长辈/家人'?'挑了一个日常能用得上的小礼物。希望你照顾好自己，也常常有轻松开心的时候。':state.answers.object==='熟人朋友'?'想到你可能会喜欢，就认真选了这一份。希望它能给最近的生活添一点方便和好心情。':'谢谢这段时间的照顾。这份小礼物不算隆重，但想把我的感谢认真地送到。';return{wrapping,surprise,timing,card}}

function openDetail(id){const x=state.results.find(i=>i.id===id)||state.near.find(i=>i.id===id)||data.items.find(i=>i.id===id);if(!x)return;state.detail=x;const advice=sendAdvice(x);const match=x.relaxed?'相近推荐':`高度匹配 · ${x.score||'—'} 分`;$('#dialog-root').innerHTML=`<div class="drawer-backdrop" data-action="close-detail"></div><aside class="drawer gift-detail" role="dialog" aria-modal="true" aria-labelledby="detail-title"><button class="drawer-close" data-action="close-detail" aria-label="关闭详情">×</button><div class="detail-hero"><div class="score">${match}</div><h2 id="detail-title">${esc(x.name)}</h2><p class="detail-price">¥${x.price[0]}–¥${x.price[1]}</p></div><div class="detail-block"><h4>为什么推荐</h4><p>${esc(x.reason)}</p><p class="detail-focus"><strong>挑选时留意：</strong>${esc(x.focus)}</p></div><section class="give-guide" aria-labelledby="give-guide-title"><div class="give-guide-head"><div><span class="kicker">HOW TO GIVE</span><h3 id="give-guide-title">把这份礼物送得更用心</h3></div></div><div class="give-guide-grid"><article><span class="give-guide-index">01</span><h4>包装方式</h4><p>${esc(advice.wrapping)}</p></article><article><span class="give-guide-index">02</span><h4>制造惊喜</h4><p>${esc(advice.surprise)}</p></article><article><span class="give-guide-index">03</span><h4>赠送时机</h4><p>${esc(advice.timing)}</p></article><article class="card-copy"><span class="give-guide-index">04</span><h4>贺卡文案</h4><p>“${esc(advice.card)}”</p><button class="mini-btn" data-copy-card="${esc(advice.card)}">复制文案</button></article></div></section></aside>`;$('.drawer-close')?.focus()}

document.addEventListener('click',e=>{const copy=e.target.closest('[data-copy-card]');if(!copy)return;navigator.clipboard?.writeText(copy.dataset.copyCard).then(()=>toast('贺卡文案已复制')).catch(()=>toast('复制失败，请手动选择文案'))});
bind();loadData().finally(render);

const resultsLayoutBase=results;results=()=>resultsLayoutBase().replace('<button class="secondary" data-action="shuffle">换一组</button>','').replace('<div class="gift-list">','<div class="asset-result-mark" aria-hidden="true"></div><div class="gift-list">').replace('<div class="send-panel">','<div class="result-bottom-actions"><span>还想看看别的组合？</span><button class="secondary" data-action="shuffle">换一组</button></div><div class="send-panel">');
const resultsSaveEntryBase=results;results=()=>resultsSaveEntryBase().replace('>分享</button>','>保存图片</button>');
const shareSaveBase=share;share=()=>shareSaveBase().replace('做一张<br>可以转发的心意卡。','预览后，保存这份心意。').replace('生成分享图','生成并保存图片');
const resultsNoResultArt=results;results=()=>resultsNoResultArt().replace('<div class="asset-result-mark" aria-hidden="true"></div>','');
const shareLayoutBase=share;share=()=>shareLayoutBase().replace('<div class="kicker">Share a little care</div>','');
const renderShareCleanBase=render;render=()=>{renderShareCleanBase();if(state.screen==='share'){$('.share-actions [data-action="save-image"]')?.remove();const generate=$('.share-actions [data-action="generate"]');if(generate)generate.textContent='保存图片';}};
document.addEventListener('click',e=>{const generate=e.target.closest('.share-actions [data-action="generate"]');if(!generate)return;e.preventDefault();e.stopImmediatePropagation();const a=document.createElement('a');a.download='送礼大王-分享图.png';a.href=drawShare();a.click();toast('图片已保存');},true);
const sharePosterCleanBase=share;share=()=>sharePosterCleanBase().replace('<h2>预览后，保存这份心意。</h2>','');
const renderPosterCleanBase=render;render=()=>{renderPosterCleanBase();if(state.screen==='share'){$('.asset-share-corner')?.remove();}};
const renderNoFeedbackBase=render;render=()=>{renderNoFeedbackBase();if(state.screen==='results')$('.feedback')?.remove();};

